spring.application.name=virtualWallet
spring.datasource.url=jdbc:mariadb://localhost:3306/virtualwallet
spring.datasource.username=root
spring.datasource.password=migue73168320128

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

